version: '3'

services:
  docker-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_atm
      - MYSQL_USER=springUser
      - MYSQL_PASSWORD=spring
    ports:
      - 3307:3306

  app:
    image: atm:1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/db_atm?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql